<a href="https://colab.research.google.com/github/aurummaangxinchen-del/S4DS-Taks/blob/main/Online_Shoppers_intention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report

In [20]:
df =pd.read_csv('/content/online_shoppers_intention.csv')
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [22]:
df = df[df['VisitorType'] != 'Other']

In [23]:
df['VisitorType'].value_counts()

VisitorType
Returning_Visitor    10551
New_Visitor           1694
Name: count, dtype: int64

In [24]:
df['Month'].value_counts()

Month
May     3364
Nov     2976
Mar     1907
Dec     1665
Oct      549
Sep      448
Aug      433
Jul      432
June     287
Feb      184
Name: count, dtype: int64

In [25]:
le = LabelEncoder()
df['VisitorType'] = le.fit_transform(df['VisitorType'])
df['Weekend'] = le.fit_transform(df['Weekend'])
df['Revenue'] = le.fit_transform(df['Revenue'])

In [26]:
df = pd.get_dummies(df,columns=['Month'],drop_first=True,dtype=int)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12245 entries, 0 to 12329
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12245 non-null  int64
 1   Administrative_Duration  12245 non-null  float64
 2   Informational            12245 non-null  int64
 3   Informational_Duration   12245 non-null  float64
 4   ProductRelated           12245 non-null  int64
 5   ProductRelated_Duration  12245 non-null  float64
 6   BounceRates              12245 non-null  float64
 7   ExitRates                12245 non-null  float64
 8   PageValues               12245 non-null  float64
 9   SpecialDay               12245 non-null  float64
 10  OperatingSystems         12245 non-null  int64
 11  Browser                  12245 non-null  int64
 12  Region                   12245 non-null  int64
 13  TrafficType              12245 non-null  int64
 14  VisitorType              12245 non-null  int64
 15  Weekend                  12245 non-null  int64
 16  Revenue                  12245 non-null  int64
 17  Month_Dec                12245 non-null  int64
 18  Month_Feb                12245 non-null  int64
 19  Month_Jul                12245 non-null  int64
 20  Month_June               12245 non-null  int64
 21  Month_Mar                12245 non-null  int64
 22  Month_May                12245 non-null  int64
 23  Month_Nov                12245 non-null  int64
 24  Month_Oct                12245 non-null  int64
 25  Month_Sep                12245 non-null  int64
dtypes: float64(7), int64(19)
memory usage: 2.5 MB

In [28]:
df['Administrative_Duration'] =df['Administrative_Duration'].astype(int)
df['Informational_Duration'] =df['Informational_Duration'].astype(int)
df['ProductRelated_Duration'] =df['ProductRelated_Duration'].astype(int)
df['BounceRates'] =df['BounceRates'].astype(int)
df['ExitRates'] =df['ExitRates'].astype(int)
df['PageValues'] =df['PageValues'].astype(int)
df['SpecialDay'] =df['SpecialDay'].astype(int)

In [29]:
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,Revenue,Month_Dec,Month_Feb,Month_Jul,Month_June,Month_Mar,Month_May,Month_Nov,Month_Oct,Month_Sep
0,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,2,64,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,2,2,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,10,627,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145,0,0,53,1783,0,0,12,0,...,0,1,0,0,0,0,0,0,0,0
12326,0,0,0,0,5,465,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12327,0,0,0,0,6,184,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12328,4,75,0,0,15,346,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12329,0,0,0,0,3,21,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [30]:
scaler =StandardScaler()
df['ProductRelated_Duration'] = scaler.fit_transform(df[['ProductRelated_Duration']])
df['Administrative_Duration'] = scaler.fit_transform(df[['Administrative_Duration']])
df['Informational_Duration'] = scaler.fit_transform(df[['Informational_Duration']])

In [31]:
X = df.drop(columns=['Revenue'])
y = df['Revenue']

In [32]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [33]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X_train_val,X_test_val,y_train_val,y_test_val = train_test_split(X_train,y_train,test_size=0.2,random_state=42)

In [39]:
depths = [3,4,5,6,7,8,9,11,15]
results=[]


for depth in depths:
  model  =DecisionTreeClassifier(max_depth=depth)
  model.fit(X_train_val,y_train_val)
  y_pred = model.predict(X_test_val)
  accuracy_test = accuracy_score(y_test_val,y_pred)
  accuracy_train  = accuracy_score(y_train_val,model.predict(X_train_val))
  print(accuracy_score(y_test_val,y_pred))
  print(classification_report(y_test_val,y_pred))


  results.append([depth,accuracy_train,accuracy_test])

0.8892857142857142
              precision    recall  f1-score   support

           0       0.92      0.95      0.93      1641
           1       0.69      0.59      0.63       319

    accuracy                           0.89      1960
   macro avg       0.80      0.77      0.78      1960
weighted avg       0.88      0.89      0.89      1960

0.8908163265306123
              precision    recall  f1-score   support

           0       0.94      0.93      0.93      1641
           1       0.66      0.67      0.67       319

    accuracy                           0.89      1960
   macro avg       0.80      0.80      0.80      1960
weighted avg       0.89      0.89      0.89      1960

0.8923469387755102
              precision    recall  f1-score   support

           0       0.93      0.94      0.94      1641
           1       0.67      0.66      0.67       319

    accuracy                           0.89      1960
   macro avg       0.80      0.80      0.80      1960
weighted avg       0.89      0.89      0.89      1960

0.889795918367347
              precision    recall  f1-score   support

           0       0.93      0.94      0.93      1641
           1       0.67      0.65      0.66       319

    accuracy                           0.89      1960
   macro avg       0.80      0.79      0.80      1960
weighted avg       0.89      0.89      0.89      1960

0.8831632653061224
              precision    recall  f1-score   support

           0       0.92      0.94      0.93      1641
           1       0.65      0.61      0.63       319

    accuracy                           0.88      1960
   macro avg       0.79      0.77      0.78      1960
weighted avg       0.88      0.88      0.88      1960

0.8806122448979592
              precision    recall  f1-score   support

           0       0.92      0.95      0.93      1641
           1       0.66      0.55      0.60       319

    accuracy                           0.88      1960
   macro avg       0.79      0.75      0.76      1960
weighted avg       0.87      0.88      0.88      1960

0.8811224489795918
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      1641
           1       0.64      0.62      0.63       319

    accuracy                           0.88      1960
   macro avg       0.78      0.77      0.78      1960
weighted avg       0.88      0.88      0.88      1960

0.8816326530612245
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      1641
           1       0.64      0.61      0.63       319

    accuracy                           0.88      1960
   macro avg       0.78      0.77      0.78      1960
weighted avg       0.88      0.88      0.88      1960

0.8642857142857143
              precision    recall  f1-score   support

           0       0.92      0.92      0.92      1641
           1       0.59      0.57      0.58       319

    accuracy                           0.86      1960
   macro avg       0.75      0.74      0.75      1960
weighted avg       0.86      0.86      0.86      1960

In [35]:
print(results)

[[3, 0.9008422664624809, 0.8892857142857142], [4, 0.9049259826442062, 0.8908163265306123], [5, 0.9072230729964268, 0.8923469387755102], [6, 0.9120724859622257, 0.889795918367347], [7, 0.9185809086268504, 0.8826530612244898], [8, 0.9252169474221542, 0.8795918367346939], [9, 0.9324910668708525, 0.8816326530612245], [11, 0.9476773864216437, 0.8785714285714286], [15, 0.97524247064829, 0.8627551020408163]]

In [36]:
model = DecisionTreeClassifier(max_depth=4)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8873009391588403
              precision    recall  f1-score   support

           0       0.94      0.93      0.93      2065
           1       0.64      0.66      0.65       384

    accuracy                           0.89      2449
   macro avg       0.79      0.80      0.79      2449
weighted avg       0.89      0.89      0.89      2449